export const navGroups = [
  {
    label: "회사소개",
    href: "/company/greeting",
    description: "기업의 신뢰와 기술 성장의 기록",
    items: [
      { label: "인사말", href: "/company/greeting" },
      { label: "주요연혁", href: "/company/history" },
      { label: "인증·특허", href: "/company/certification" },
      { label: "오시는 길", href: "/company/location" },
    ],
  },
  {
    label: "사업분야",
    href: "/business",
    description: "Valve · Actuator · Engineering · R&D",
    items: [
      { label: "Valve", href: "/business#valve" },
      { label: "Actuator", href: "/business#actuator" },
      { label: "Engineering Service", href: "/business#engineering" },
      { label: "R&D", href: "/business#rnd" },
    ],
  },
  {
    label: "제품소개",
    href: "/products",
    description: "극한 환경을 위한 제품 포트폴리오",
    items: [
      { label: "Cryogenic Valve", href: "/products/cryogenic" },
      { label: "Special Valve for Gas", href: "/products/special-gas" },
      { label: "Liquid Hydrogen Valve", href: "/products/liquid-hydrogen" },
      { label: "High Temp. & High Pr.", href: "/products/high-temp" },
      { label: "Back Wash Filter", href: "/products/back-wash-filter" },
    ],
  },
  {
    label: "기술력",
    href: "/technology/cryogenic",
    description: "극저온·초고압·품질 검증 기술",
    items: [
      { label: "극저온·초고압 기술", href: "/technology/cryogenic" },
      { label: "설계개발·엔지니어링", href: "/technology/engineering" },
      { label: "품질·시험·인증 체계", href: "/technology/quality" },
    ],
  },
  {
    label: "납품실적",
    href: "/performance",
    description: "산업 현장에서 검증된 프로젝트",
    items: [
      { label: "주요 프로젝트", href: "/performance" },
      { label: "LNG / 가스", href: "/performance#projects" },
      { label: "수소 / 암모니아", href: "/performance#projects" },
      { label: "수출·공급 이력", href: "/performance#projects" },
    ],
  },
  {
    label: "고객지원",
    href: "/support/notice",
    description: "공지·자료·기술 상담을 빠르게",
    items: [
      { label: "공지사항", href: "/support/notice" },
      { label: "자료실", href: "/support/library" },
      { label: "온라인 문의", href: "/support/contact" },
      { label: "오시는 길", href: "/company/location" },
    ],
  },
];

export const businessAreas = [
  { id: "valve", no: "01", title: "Valve", copy: "극저온 및 고압 가스용 특수 밸브 설계·제작", detail: "LNG · LN2 · LH2 · Methanol · Ammonia · H₂ · NG", icon: "V" },
  { id: "actuator", no: "02", title: "Actuator", copy: "정밀 제어를 위한 자동제어 밸브 및 구동 솔루션", detail: "Pneumatic · Electric · On/Off · Control", icon: "A" },
  { id: "engineering", no: "03", title: "Technical Support & Engineering Service", copy: "요구조건 검토부터 설계·제작·시험까지 고객 맞춤형 기술지원", detail: "Design Review · Selection · Drawing · Technical Support", icon: "E" },
  { id: "rnd", no: "04", title: "R&D", copy: "차세대 에너지 환경을 위한 극한 조건 밸브 기술 개발", detail: "Cryogenic · Hydrogen · Ammonia · High Pressure", icon: "R" },
];

export const products = [
  {
    slug: "cryogenic",
    title: "Cryogenic Valve",
    kicker: "LNG · LN2",
    temperature: "-196℃",
    pressure: "350 bar",
    size: "1/2” – 16”",
    standard: "ASME B16.34 · ISO 21011 (BS 6364) · KGS AA335 · ISO 9001",
    description: "LNG, LN2 등 극저온(-196℃) 가스용 밸브로 국제 기술기준에 따라 설계·제작 및 성능인증된 제품입니다. 사용자 요구조건에 따라 최대 350bar까지 적용할 수 있습니다.",
    accent: "cyan",
    specs: [
      ["Valve Type", "Globe & Angle"],
      ["Valve Size", "1/2”~16” (15A~400A)"],
      ["Body Rating", "ASME B16.34, #150~#2500"],
      ["Face-to-Face", "ASME B16.10"],
      ["Body Connection", "BW, RF, RTJ Type"],
      ["Body / Bonnet Material", "A182-F316(L), A276-316(L), A351-CF8, A351-CF8M, Special Alloy, Etc."],
      ["Trim Material", "STS316, STS410, Special Alloy (Titanium, Etc.)"],
      ["Gasket / Packing", "Spiral wound gasket with PTFE or Graphite / V-PTFE, Graphite, Etc."],
      ["Flow Characteristics", "EQ %, Linear, Quick Opening"],
      ["Seat Leakage", "Soft Seat: ANSI Class VI / Metal Seat: ANSI Class IV"],
      ["Applicable Standards", "ASME B16.34, ISO 21011 (BS 6364), KGS AA335, ISO 9001"],
    ],
  },
  {
    slug: "special-gas",
    title: "Special Valve for Gas",
    kicker: "LPG · NG · H2 · Methanol · Ammonia",
    temperature: "Gas Service",
    pressure: "1000 bar",
    size: "3/4” – 16”",
    standard: "ASME B16.34 · ISO 5208 · API 598 · KGS AA317 · ISO 9001",
    description: "LPG, NG, H2, Methanol, Ammonia 가스용 밸브로 국제 기술기준에 따라 설계·제작 및 성능인증된 제품입니다. 특히 H2 가스용 밸브는 최대 1000bar까지 적용할 수 있습니다.",
    accent: "blue",
    specs: [
      ["Application", "LPG, NG, H2, Methanol, Ammonia"],
      ["Valve Type", "Globe & Angle"],
      ["Valve Size", "3/4”~16” (20A~400A)"],
      ["Body Rating", "ASME B16.34, #150~#4500, JIS 10K/20K"],
      ["Face-to-Face", "ASME B16.10"],
      ["Body Connection", "BW, RF, RTJ"],
      ["Body / Bonnet Material", "A216-WCB, A182-F304, A182-F316, A351-CF8, A351-CF8M, Special Alloy, Etc."],
      ["Trim Material", "STS316, STS410, Special Alloy (Titanium, Etc.)"],
      ["Gasket / Packing", "Spiral wound gasket with PTFE or Graphite / V-PTFE, Graphite, Etc."],
      ["Flow Characteristics", "EQ %, Linear, Quick Opening"],
      ["Seat Leakage", "Soft Seat: ANSI Class VI / Metal Seat: ANSI Class IV"],
      ["Applicable Standards", "ASME B16.34, ISO 5208, API 598, KGS AA317, ISO 9001"],
    ],
  },
  {
    slug: "liquid-hydrogen",
    title: "Cryogenic Valve for Liquid Hydrogen",
    kicker: "Liquid Hydrogen · LH2",
    temperature: "-253℃",
    pressure: "#150 – #600",
    size: "1” – 3”",
    standard: "ASME B16.34 · ISO 21011 (BS 6364) · KGS AA335 · ISO 9001 · KR10-2509774",
    description: "극저온(-253℃) 액화수소용 밸브로 국제 기술기준과 특허기술 KR10-2509774를 적용했습니다. 용접부가 없는 일체형 BODY와 진공단열 구조를 적용하여 극저온 환경에서의 누설 방지와 열전달 저감을 고려한 제품입니다.",
    accent: "violet",
    specs: [
      ["Service", "Liquid Hydrogen (LH2), -253℃"],
      ["Valve Type", "Globe & Angle"],
      ["Valve Size", "1”~3” (25A~80A)"],
      ["Body Rating", "ASME B16.34, #150~#600"],
      ["Face-to-Face", "ASME B16.10"],
      ["Body Connection", "BW, RF, RTJ Type"],
      ["Body / Bonnet Material", "A182-F316(L), A276-316(L), A351-CF3, A351-CF3M, Special Alloy, Etc."],
      ["Trim Material", "STS316, STS410, Special Alloy (Titanium, Etc.)"],
      ["Flow Characteristics", "EQ %, Linear, Quick Opening"],
      ["Seat Leakage", "Soft Seat: ANSI Class VI / Metal Seat: ANSI Class IV"],
      ["Design Feature", "Integral BODY, Vacuum Insulation, Bellows Seal"],
      ["Patent / Standards", "KR10-2509774 / ASME B16.34 / ISO 21011 (BS 6364) / KGS AA335 / ISO 9001"],
    ],
  },
  {
    slug: "high-temp",
    title: "High Temp. & High Pressure Control Valve",
    kicker: "Steam · High Temp. · High Pressure",
    temperature: "600℃",
    pressure: "500 bar",
    size: "1/2” – 20”",
    standard: "ASME B16.34 · KEPIC MGG · API 598 · ISO 5208 · ISO 9001",
    description: "증기 및 고온·고압 공정용 제어밸브로 국제 기술기준에 따라 설계·제작 및 성능인증된 제품입니다. 사용자 요구조건에 따라 최대온도 600℃ 및 최대압력 500bar까지 적용할 수 있습니다.",
    accent: "green",
    specs: [
      ["Service", "Steam / High Temperature & High Pressure Process"],
      ["Valve Type", "Globe & Angle"],
      ["Valve Size", "1/2”~20” (15A~500A)"],
      ["Body Rating", "ASME B16.34, #150~#4500, JIS 10K/20K"],
      ["Face-to-Face", "ASME B16.10"],
      ["Body Connection", "BW, RF, RTJ"],
      ["Temperature", "-40~600℃"],
      ["Maximum Pressure", "Up to 500bar"],
      ["Body / Bonnet Material", "A216-WCB, A182-F304, A182-F316, A351-CF8, A351-CF8M, Special Alloy, Etc."],
      ["Trim Material", "STS316, STS410, Special Alloy (Titanium, Etc.)"],
      ["Flow Characteristics", "EQ %, Linear, Quick Opening"],
      ["Seat Leakage", "Soft Seat: ANSI Class VI / Metal Seat: ANSI Class IV"],
      ["Applicable Standards", "ASME B16.34, KEPIC MGG, API 598, ISO 5208, ISO 9001"],
    ],
  },
  {
    slug: "back-wash-filter",
    title: "Back Wash Filter",
    kicker: "Sea Water · Fresh Water · Auto Back Wash",
    temperature: "30℃",
    pressure: "2 – 7 bar",
    size: "DN100",
    standard: "ASME Sec. III or VIII · API 598 · ISO 9001",
    description: "유체 내 이물질을 제거하는 자동 역세척 여과장치로 국제 기술기준에 따라 설계·제작 및 성능인증된 제품입니다. 정상 운전 중 자동세척 기능을 수행하며 해수 및 담수 설비에 적용할 수 있습니다.",
    accent: "orange",
    specs: [
      ["Datasheet Basis", "Auto Back Wash Filter for Sea Water (Representative Data)"],
      ["Model / Type", "BW Filter / Basket (Cylindrical)"],
      ["Fluid", "Sea Water (Fresh Water application available)"],
      ["Housing / Filter Material", "STS316L / S32205 (Super Duplex SS2205)"],
      ["Nominal Size", "DN100"],
      ["Design Pressure", "PN10"],
      ["Minimum Inlet Pressure", "2.6bar"],
      ["Design / Operating Temperature", "45℃ / 30℃"],
      ["Automatic Operation ΔP", ">0.5~0.7bar"],
      ["Nominal Flow", "500 LPM at Δp 0.2bar"],
      ["Mesh Pore Size", "400μm (Max./Min. 420/380μm)"],
      ["Operating Pressure", "2~7bar"],
      ["Backwash Time", "30 sec @ 0.7bar"],
      ["Adjustable Differential Pressure", "0.2~1.0bar"],
      ["Connection", "ISO7005-1 DN100 / PN10, Backwash Drain DN50 / PN10"],
      ["Protection / Motor", "IP65 / Motor IP55, 380V, 50/60Hz, ~180W"],
      ["Applicable Standards", "ASME Sec. III or VIII, API 598, ISO 9001"],
    ],
  },
];

export const projects = [
  { slug: "lng-bunkering", year: "2024", country: "대한민국", title: "LNG 벙커링 설비 초저온 밸브 공급", product: "Cryogenic Valve", summary: "LNG 이송라인의 극저온 조건에 대응하는 밸브 설계 및 공급", tag: "LNG / GAS" },
  { slug: "liquid-hydrogen", year: "2025", country: "대한민국", title: "액화수소 설비용 극저온 제어밸브 공급", product: "Liquid Hydrogen Valve", summary: "-253℃ 액화수소 환경을 고려한 극저온 밸브 적용", tag: "HYDROGEN" },
  { slug: "india-nuclear-filter", year: "2025", country: "인도", title: "인도 원전용 Back Wash Filter 공급", product: "Back Wash Filter", summary: "원전 보조계통용 자동 역세척 여과장치 설계·제작", tag: "EXPORT" },
  { slug: "high-pressure-plant", year: "2024", country: "대한민국", title: "고온·고압 플랜트 제어밸브 공급", product: "High Temp. & High Pressure Control Valve", summary: "고온 증기 및 고압 라인 조건에 대응하는 제어밸브 공급", tag: "PLANT" },
  { slug: "bv-cryogenic", year: "2023", country: "대한민국", title: "BV 인증 대응 초저온 밸브 제작", product: "Cryogenic Valve", summary: "선박 및 가스 설비 적용을 위한 초저온 밸브 제작·시험", tag: "MARINE" },
  { slug: "hydrogen-control", year: "2024", country: "대한민국", title: "수소 생산·공급설비 자동제어 밸브 개발", product: "Special Valve for Gas", summary: "고압 수소 공정의 제어 안정성과 기밀성을 고려한 밸브 개발", tag: "R&D" },
];

export const technologies = {
  cryogenic: {
    eyebrow: "Technology 01",
    title: "극저온·초고압 기술",
    headline: "Extreme Environment Valve Technology",
    intro: "-196℃ LNG/LN2부터 -253℃ LH₂, 최대 1000bar 수소가스까지 극한 운전 조건에서도 안정적인 작동을 목표로 설계합니다.",
    metrics: [["-253℃", "Liquid Hydrogen"], ["1000 bar", "Hydrogen Gas"], ["500 bar", "High Pressure"], ["600℃", "High Temperature"]],
    points: [["Cryogenic Design", "열전달 최소화와 장축 구조를 고려한 극저온 설계"], ["Leak Prevention", "Bellows Seal, 양방향 밀봉, 일체형 Body 구조"], ["Vacuum Insulation", "Vacuum Jacket 적용을 통한 외부 열 유입 저감"], ["Material Engineering", "사용 유체·온도·압력에 맞춘 재질 및 Trim 선정"]],
  },
  engineering: {
    eyebrow: "Technology 02",
    title: "설계개발·엔지니어링",
    headline: "From Requirement to Reliable Operation",
    intro: "유체, 온도, 압력, 규격, 연결방식과 현장 조건을 검토하여 제품 선정부터 설계·시험·기술지원까지 연결합니다.",
    metrics: [["01", "Requirement"], ["02", "Engineering"], ["03", "Manufacturing"], ["04", "Testing"]],
    points: [["요구조건 검토", "P&ID, Datasheet, 운전 조건 및 적용 규격 검토"], ["설계·도면", "고객 요구에 맞춘 제품 선정 및 도면 검토"], ["제작·조립", "공정 및 품질 기준에 따른 제작과 조립"], ["시험·지원", "성능시험, 누설시험 및 납품 후 기술지원"]],
  },
  quality: {
    eyebrow: "Technology 03",
    title: "품질·시험·인증 체계",
    headline: "Verified Quality for Critical Applications",
    intro: "국제 표준과 프로젝트 요구조건을 기준으로 설계·제작·시험 이력을 관리하고 제품별 품질 검증 체계를 운영합니다.",
    metrics: [["ISO 9001", "Quality System"], ["API 598", "Valve Inspection"], ["ISO 5208", "Pressure Testing"], ["KGS", "Gas Equipment"]],
    points: [["Design Standard", "ASME B16.34, ISO 21011, BS 6364 등 적용"], ["Performance Test", "압력·누설·작동 성능 시험 및 검사"], ["Cryogenic Test", "극저온 조건을 고려한 성능 검증"], ["Traceability", "재질, 제작, 검사 데이터 추적 및 문서화"]],
  },
};