export const navGroups = [
  {
    label: "회사소개",
    href: "/company/greeting",
    description: "기업의 신뢰와 기술 성장의 기록",
    items: [
      { label: "인사말", href: "/company/greeting" },
      { label: "주요연혁", href: "/company/history" },
      { label: "인증·특허", href: "/company/certification" },
      { label: "오시는 길", href: "/company/location" },
    ],
  },
  {
    label: "사업분야",
    href: "/business",
    description: "Valve · Automation Machinery · Engineering · R&D",
    items: [
      { label: "Valve", href: "/business#valve" },
      { label: "Automation Machinery", href: "/business#automation" },
      { label: "Engineering Service", href: "/business#engineering" },
      { label: "R&D", href: "/business#rnd" },
    ],
  },
  {
    label: "제품소개",
    href: "/products",
    description: "특수 밸브·필터·자동화기계 제품 포트폴리오",
    items: [
      { label: "Cryogenic Valve", href: "/products/cryogenic" },
      { label: "High Temp. & High Pr.", href: "/products/high-temp" },
      { label: "Special Valve for Gas", href: "/products/special-gas" },
      { label: "Auto Back Wash Filter", href: "/products/back-wash-filter" },
      { label: "Automation Machinery", href: "/products/automation-machinery" },
    ],
  },
  {
    label: "기술력",
    href: "/technology/cryogenic",
    description: "극저온·초고압·엔지니어링·품질 검증 기술",
    items: [
      { label: "극저온·초고압 기술", href: "/technology/cryogenic" },
      { label: "설계개발·엔지니어링", href: "/technology/engineering" },
      { label: "품질·시험·인증 체계", href: "/technology/quality" },
    ],
  },
  {
    label: "납품실적",
    href: "/performance",
    description: "산업 현장에서 검증된 프로젝트",
    items: [
      { label: "주요 프로젝트", href: "/performance" },
      { label: "LNG / 가스", href: "/performance#projects" },
      { label: "원자력 / Filter", href: "/performance#projects" },
      { label: "수출·공급 이력", href: "/performance#projects" },
    ],
  },
  {
    label: "고객지원",
    href: "/support/notice",
    description: "공지·자료·기술 상담을 빠르게",
    items: [
      { label: "공지사항", href: "/support/notice" },
      { label: "자료실", href: "/support/library" },
      { label: "온라인 문의", href: "/support/contact" },
      { label: "오시는 길", href: "/company/location" },
    ],
  },
];

export const businessAreas = [
  { id: "valve", no: "01", title: "Valve", copy: "극저온 및 고압 환경용 특수 밸브 설계·제작", detail: "LNG · LN2 · LH2 · Methanol · Ammonia · H2 · NG", icon: "V" },
  { id: "automation", no: "02", title: "Automation Machinery", copy: "자동화 설비와 Fluid Device 기반 장비 개발·제작", detail: "Auto Back Wash Filter · 폐어구 무인 반납장치 · 파쇄기", icon: "A" },
  { id: "engineering", no: "03", title: "Technical Support & Engineering Service", copy: "설계검토와 해석을 포함한 고객 맞춤형 기술지원", detail: "Seismic · Flow · Actuation Analysis · Design Review · Technical Support", icon: "E" },
  { id: "rnd", no: "04", title: "R&D", copy: "차세대 에너지·원자력·자동화 분야 기술 개발", detail: "Cryogenic · Hydrogen · Nuclear · Automation", icon: "R" },
];

export const products = [
  {
    slug: "cryogenic",
    featured: true,
    title: "Cryogenic Valve",
    kicker: "LNG · LN2 · Cryogenic",
    temperature: "-196℃",
    pressure: "350 bar",
    size: "1/2” – 16”",
    standard: "ASME B16.34 · ISO 21011 (BS 6364) · KGS AA335 · ISO 9001",
    description: "LNG, LN2 등 극저온(-196℃) 가스용 밸브로 국제 기술기준에 따라 설계·제작 및 성능인증된 제품입니다. 사용자 요구조건에 따라 최대 350bar까지 적용할 수 있으며 액화수소용 극저온 밸브 기술도 함께 보유하고 있습니다.",
    accent: "cyan",
    media: [
      ["제품 대표 이미지", "Cryogenic Valve 대표 제품 이미지 등록 영역"],
      ["초저온 밸브 시험 영상", "극저온 조건 성능시험 영상 등록 영역"],
      ["밸브 작동 영상", "밸브 구동 및 작동 특성 영상 등록 영역"],
    ],
    specs: [
      ["Valve Type", "Globe & Angle"],
      ["Valve Size", "1/2”~16” (15A~400A)"],
      ["Body Rating", "ASME B16.34, #150~#2500"],
      ["Face-to-Face", "ASME B16.10"],
      ["Body Connection", "BW, RF, RTJ Type"],
      ["Body / Bonnet Material", "A182-F316(L), A276-316(L), A351-CF8, A351-CF8M, Special Alloy, Etc."],
      ["Trim Material", "STS316, STS410, Special Alloy (Titanium, Etc.)"],
      ["Gasket / Packing", "Spiral wound gasket with PTFE or Graphite / V-PTFE, Graphite, Etc."],
      ["Flow Characteristics", "EQ %, Linear, Quick Opening"],
      ["Seat Leakage", "Soft Seat: ANSI Class VI / Metal Seat: ANSI Class IV"],
      ["Applicable Standards", "ASME B16.34, ISO 21011 (BS 6364), KGS AA335, ISO 9001"],
    ],
  },
  {
    slug: "high-temp",
    featured: true,
    title: "High Temp. & High Pressure Control Valve",
    kicker: "Steam · High Temp. · High Pressure",
    temperature: "600℃",
    pressure: "500 bar",
    size: "1/2” – 20”",
    standard: "ASME B16.34 · KEPIC MGG · API 598 · ISO 5208 · ISO 9001",
    description: "증기 및 고온·고압 공정용 제어밸브로 국제 기술기준에 따라 설계·제작 및 성능인증된 제품입니다. 사용자 요구조건에 따라 최대온도 600℃ 및 최대압력 500bar까지 적용할 수 있습니다.",
    accent: "green",
    media: [
      ["제품 대표 이미지", "고온·고압 제어밸브 대표 이미지 등록 영역"],
      ["밸브 작동 영상", "제어밸브 구동 및 작동 영상 등록 영역"],
      ["성능 시험 자료", "제품 성능시험 사진 또는 영상 등록 영역"],
    ],
    specs: [
      ["Service", "Steam / High Temperature & High Pressure Process"],
      ["Valve Type", "Globe & Angle"],
      ["Valve Size", "1/2”~20” (15A~500A)"],
      ["Body Rating", "ASME B16.34, #150~#4500, JIS 10K/20K"],
      ["Face-to-Face", "ASME B16.10"],
      ["Body Connection", "BW, RF, RTJ"],
      ["Temperature", "-40~600℃"],
      ["Maximum Pressure", "Up to 500bar"],
      ["Body / Bonnet Material", "A216-WCB, A182-F304, A182-F316, A351-CF8, A351-CF8M, Special Alloy, Etc."],
      ["Trim Material", "STS316, STS410, Special Alloy (Titanium, Etc.)"],
      ["Flow Characteristics", "EQ %, Linear, Quick Opening"],
      ["Seat Leakage", "Soft Seat: ANSI Class VI / Metal Seat: ANSI Class IV"],
      ["Applicable Standards", "ASME B16.34, KEPIC MGG, API 598, ISO 5208, ISO 9001"],
    ],
  },
  {
    slug: "special-gas",
    featured: true,
    title: "Special Valve for Gas",
    kicker: "LPG · NG · H2 · Methanol · Ammonia",
    temperature: "Gas Service",
    pressure: "1000 bar",
    size: "3/4” – 16”",
    standard: "ASME B16.34 · ISO 5208 · API 598 · KGS AA317 · ISO 9001",
    description: "LPG, NG, H2, Methanol, Ammonia 가스용 밸브로 국제 기술기준에 따라 설계·제작 및 성능인증된 제품입니다. 특히 H2 가스용 밸브는 최대 1000bar까지 적용할 수 있습니다.",
    accent: "blue",
    media: [
      ["제품 대표 이미지", "가스용 특수밸브 대표 이미지 등록 영역"],
      ["밸브 작동 영상", "밸브 구동 및 제어 영상 등록 영역"],
      ["성능 시험 자료", "기밀 및 성능시험 사진 또는 영상 등록 영역"],
    ],
    specs: [
      ["Application", "LPG, NG, H2, Methanol, Ammonia"],
      ["Valve Type", "Globe & Angle"],
      ["Valve Size", "3/4”~16” (20A~400A)"],
      ["Body Rating", "ASME B16.34, #150~#4500, JIS 10K/20K"],
      ["Face-to-Face", "ASME B16.10"],
      ["Body Connection", "BW, RF, RTJ"],
      ["Body / Bonnet Material", "A216-WCB, A182-F304, A182-F316, A351-CF8, A351-CF8M, Special Alloy, Etc."],
      ["Trim Material", "STS316, STS410, Special Alloy (Titanium, Etc.)"],
      ["Gasket / Packing", "Spiral wound gasket with PTFE or Graphite / V-PTFE, Graphite, Etc."],
      ["Flow Characteristics", "EQ %, Linear, Quick Opening"],
      ["Seat Leakage", "Soft Seat: ANSI Class VI / Metal Seat: ANSI Class IV"],
      ["Applicable Standards", "ASME B16.34, ISO 5208, API 598, KGS AA317, ISO 9001"],
    ],
  },
  {
    slug: "back-wash-filter",
    featured: true,
    title: "Auto Back Wash Filter",
    kicker: "Sea Water · Fresh Water · Auto Back Wash",
    temperature: "30℃",
    pressure: "2 – 7 bar",
    size: "DN100",
    standard: "ASME Sec. III or VIII · API 598 · ISO 9001",
    description: "유체 내 이물질을 제거하는 자동 역세척 여과장치로 국제 기술기준에 따라 설계·제작 및 성능인증된 제품입니다. 정상 운전 중 자동세척 기능을 수행하며 해수 및 담수 설비에 적용할 수 있습니다.",
    accent: "orange",
    media: [
      ["필터 대표 이미지", "Auto Back Wash Filter 대표 제품 이미지 등록 영역"],
      ["필터 작동 사진", "역세척 작동 및 시운전 사진 등록 영역"],
      ["필터 작동 영상", "자동 역세척 작동 원리 영상 등록 영역"],
    ],
    specs: [
      ["Datasheet Basis", "Auto Back Wash Filter for Sea Water (Representative Data)"],
      ["Model / Type", "BW Filter / Basket (Cylindrical)"],
      ["Fluid", "Sea Water (Fresh Water application available)"],
      ["Housing / Filter Material", "STS316L / S32205 (Super Duplex SS2205)"],
      ["Nominal Size", "DN100"],
      ["Design Pressure", "PN10"],
      ["Minimum Inlet Pressure", "2.6bar"],
      ["Design / Operating Temperature", "45℃ / 30℃"],
      ["Automatic Operation ΔP", ">0.5~0.7bar"],
      ["Nominal Flow", "500 LPM at Δp 0.2bar"],
      ["Mesh Pore Size", "400μm (Max./Min. 420/380μm)"],
      ["Operating Pressure", "2~7bar"],
      ["Backwash Time", "30 sec @ 0.7bar"],
      ["Adjustable Differential Pressure", "0.2~1.0bar"],
      ["Connection", "ISO7005-1 DN100 / PN10, Backwash Drain DN50 / PN10"],
      ["Protection / Motor", "IP65 / Motor IP55, 380V, 50/60Hz, ~180W"],
      ["Applicable Standards", "ASME Sec. III or VIII, API 598, ISO 9001"],
    ],
  },
  {
    slug: "automation-machinery",
    featured: true,
    title: "Automation Machinery",
    kicker: "Automation Machinery · Fluid Device",
    temperature: "Automation",
    pressure: "Fluid Device",
    size: "Project Based",
    standard: "Project-specific specification",
    description: "투와이젠의 자동화기계 분야는 Auto Back Wash Filter와 폐어구 무인 반납장치 등 자동화 설비 및 Fluid Device를 포함합니다. 파쇄기 등 관련 장비를 함께 구성하여 현장 목적에 맞는 자동화 시스템을 제공합니다.",
    accent: "navy",
    media: [
      ["폐어구 무인 반납장치", "폐어구 무인 반납장치 사진 등록 영역"],
      ["파쇄기", "자동화기계 분야 파쇄기 사진 등록 영역"],
      ["자동화 설비 작동 자료", "자동화 시스템 작동 사진 또는 영상 등록 영역"],
    ],
    specs: [
      ["Business Category", "Automation Machinery & Fluid Device"],
      ["Representative Equipment", "폐어구 무인 반납장치"],
      ["Related Equipment", "파쇄기 / Auto Back Wash Filter"],
      ["Engineering", "설계·제작·제어 시스템 구성"],
      ["Specification", "프로젝트 및 현장 요구조건에 따라 개별 검토"],
    ],
  },
  {
    slug: "liquid-hydrogen",
    featured: false,
    title: "Cryogenic Valve for Liquid Hydrogen",
    kicker: "Liquid Hydrogen · LH2",
    temperature: "-253℃",
    pressure: "#150 – #600",
    size: "1” – 3”",
    standard: "ASME B16.34 · ISO 21011 (BS 6364) · KGS AA335 · ISO 9001 · KR10-2509774",
    description: "극저온(-253℃) 액화수소용 밸브로 국제 기술기준과 특허기술 KR10-2509774를 적용했습니다. 용접부가 없는 일체형 BODY와 진공단열 구조를 적용하여 극저온 환경에서의 누설 방지와 열전달 저감을 고려한 제품입니다.",
    accent: "violet",
    media: [
      ["액화수소용 밸브 이미지", "LH2 Control Valve 대표 이미지 등록 영역"],
      ["초극저온 시험 자료", "-253℃ 조건 시험 사진 또는 영상 등록 영역"],
      ["밸브 작동 영상", "액화수소용 밸브 작동 영상 등록 영역"],
    ],
    specs: [
      ["Service", "Liquid Hydrogen (LH2), -253℃"],
      ["Valve Type", "Globe & Angle"],
      ["Valve Size", "1”~3” (25A~80A)"],
      ["Body Rating", "ASME B16.34, #150~#600"],
      ["Face-to-Face", "ASME B16.10"],
      ["Body Connection", "BW, RF, RTJ Type"],
      ["Body / Bonnet Material", "A182-F316(L), A276-316(L), A351-CF3, A351-CF3M, Special Alloy, Etc."],
      ["Trim Material", "STS316, STS410, Special Alloy (Titanium, Etc.)"],
      ["Flow Characteristics", "EQ %, Linear, Quick Opening"],
      ["Seat Leakage", "Soft Seat: ANSI Class VI / Metal Seat: ANSI Class IV"],
      ["Design Feature", "Integral BODY, Vacuum Insulation, Bellows Seal"],
      ["Patent / Standards", "KR10-2509774 / ASME B16.34 / ISO 21011 (BS 6364) / KGS AA335 / ISO 9001"],
    ],
  },
];

export const projects = [
  { slug: "lng-bunkering", year: "2024", country: "대한민국", title: "LNG 벙커링 설비 초저온 밸브 공급", product: "Cryogenic Valve", summary: "LNG 이송라인의 극저온 조건에 대응하는 밸브 설계 및 공급", tag: "LNG / GAS" },
  { slug: "liquid-hydrogen", year: "2025", country: "대한민국", title: "액화수소 설비용 극저온 제어밸브 공급", product: "Liquid Hydrogen Valve", summary: "-253℃ 액화수소 환경을 고려한 극저온 밸브 적용", tag: "HYDROGEN" },
  { slug: "india-nuclear-filter", year: "2025", country: "인도", title: "인도 원전용 Auto Back Wash Filter 공급", product: "Auto Back Wash Filter", summary: "원전 보조계통용 자동 역세척 여과장치 설계·제작 및 수출", tag: "NUCLEAR / EXPORT" },
  { slug: "high-pressure-plant", year: "2024", country: "대한민국", title: "고온·고압 플랜트 제어밸브 공급", product: "High Temp. & High Pressure Control Valve", summary: "고온 증기 및 고압 라인 조건에 대응하는 제어밸브 공급", tag: "PLANT" },
  { slug: "bv-cryogenic", year: "2023", country: "대한민국", title: "BV 인증 대응 초저온 밸브 제작", product: "Cryogenic Valve", summary: "선박 및 가스 설비 적용을 위한 초저온 밸브 제작·시험", tag: "MARINE" },
  { slug: "hydrogen-control", year: "2024", country: "대한민국", title: "수소 생산·공급설비 자동제어 밸브 개발", product: "Special Valve for Gas", summary: "고압 수소 공정의 제어 안정성과 기밀성을 고려한 밸브 개발", tag: "R&D" },
];

export const technologies = {
  cryogenic: {
    eyebrow: "Technology 01",
    title: "극저온·초고압 기술",
    headline: "Extreme Environment Valve Technology",
    intro: "-196℃ LNG/LN2부터 -253℃ LH2, 최대 1000bar 수소가스까지 극한 운전 조건에서도 안정적인 작동을 목표로 설계합니다.",
    metrics: [["-253℃", "Liquid Hydrogen"], ["1000 bar", "Hydrogen Gas"], ["500 bar", "High Pressure"], ["600℃", "High Temperature"]],
    points: [["Cryogenic Design", "열전달 최소화와 장축 구조를 고려한 극저온 설계"], ["Leak Prevention", "Bellows Seal, 양방향 밀봉, 일체형 Body 구조"], ["Vacuum Insulation", "Vacuum Jacket 적용을 통한 외부 열 유입 저감"], ["Material Engineering", "사용 유체·온도·압력에 맞춘 재질 및 Trim 선정"]],
  },
  engineering: {
    eyebrow: "Technology 02",
    title: "설계개발·엔지니어링",
    headline: "From Requirement to Reliable Operation",
    intro: "유체, 온도, 압력, 규격, 연결방식과 현장 조건을 검토하고 내진해석·유동해석·구동해석을 포함한 엔지니어링 기술지원을 제공합니다.",
    metrics: [["01", "Seismic"], ["02", "Flow"], ["03", "Actuation"], ["04", "Engineering"]],
    points: [["내진해석", "설비 및 장비의 지진하중 조건을 고려한 구조 검토"], ["유동해석", "유체 흐름과 압력 조건을 검토하는 해석 지원"], ["구동해석", "밸브 및 자동제어 장비의 구동 조건 검토"], ["설계·기술지원", "요구조건 검토, 제품 선정, 도면 및 기술문서 지원"]],
  },
  quality: {
    eyebrow: "Technology 03",
    title: "품질·시험·인증 체계",
    headline: "Verified Quality for Critical Applications",
    intro: "국제 표준과 프로젝트 요구조건을 기준으로 설계·제작·시험 이력을 관리하고 제품별 품질 검증 체계를 운영합니다.",
    metrics: [["ISO 9001", "Quality System"], ["API 598", "Valve Inspection"], ["ISO 5208", "Pressure Testing"], ["KGS", "Gas Equipment"]],
    points: [["Design Standard", "ASME B16.34, ISO 21011, BS 6364 등 적용"], ["Performance Test", "압력·누설·작동 성능 시험 및 검사"], ["Cryogenic Test", "극저온 조건을 고려한 성능 검증"], ["Traceability", "재질, 제작, 검사 데이터 추적 및 문서화"]],
  },
};
